// AdvLink plans: one product, two billing cycles. Change the prices here (and on the landing page).
export type BillingCycle = "MONTHLY" | "YEARLY"

export const BILLING_CYCLES: readonly BillingCycle[] = ["MONTHLY", "YEARLY"] as const

/** Business days to pay a boleto generated by the payment link. */
const BOLETO_DUE_DATE_LIMIT_DAYS = 3

export const PLANS = {
  MONTHLY: {
    cycle: "MONTHLY",
    valueCents: 4900,
    name: "AdvLink — site profissional (mensal)",
    description: "Assinatura mensal do seu site profissional AdvLink",
    /** Months covered by each paid charge. */
    months: 1,
    boletoDueDateLimitDays: BOLETO_DUE_DATE_LIMIT_DAYS,
  },
  YEARLY: {
    cycle: "YEARLY",
    valueCents: 49000,
    name: "AdvLink — site profissional (anual)",
    description: "Assinatura anual do seu site profissional AdvLink (equivale a 2 meses grátis)",
    months: 12,
    boletoDueDateLimitDays: BOLETO_DUE_DATE_LIMIT_DAYS,
  },
} as const satisfies Record<BillingCycle, { cycle: BillingCycle; valueCents: number; name: string; description: string; months: number; boletoDueDateLimitDays: number }>

/** The monthly plan (the default; kept for existing callers). */
export const PLAN = PLANS.MONTHLY

/** Unknown/missing values (legacy rows) are monthly. */
export function normalizeCycle(cycle: string | null | undefined): BillingCycle {
  return cycle === "YEARLY" ? "YEARLY" : "MONTHLY"
}

/** "/mês" or "/ano", for prices shown next to a value. */
export function cycleSuffix(cycle: string | null | undefined): string {
  return normalizeCycle(cycle) === "YEARLY" ? "/ano" : "/mês"
}

/** Monthly-equivalent value of a subscription (MRR contribution). */
export function monthlyEquivalentCents(valueCents: number, cycle: string | null | undefined): number {
  return normalizeCycle(cycle) === "YEARLY" ? Math.round(valueCents / 12) : valueCents
}

/** Days after the first payment in which the lawyer can withdraw with a full refund (manual, via support/Asaas). */
export const REFUND_WINDOW_DAYS = 7

export function formatBRL(cents: number): string {
  return (cents / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })
}
