// The single AdvLink plan. Change the price here (and on the landing page).
export const PLAN = {
  valueCents: 4900,
  name: "AdvLink — site profissional",
  description: "Assinatura mensal do seu site profissional AdvLink",
  /** Business days to pay a boleto generated by the payment link. */
  boletoDueDateLimitDays: 3,
} as const

export function formatBRL(cents: number): string {
  return (cents / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })
}
